### ISSUE TITLE
Give me error when i run

### ISSUE THREAD

**Issue by jaa-odoo** [burhan/knet-client#12]
Badzipfile

/knet/test/knet-client-master/knet/api.py", line 126, in parse
    raise zipfile.BadZipfile
BadZipfile

**Comment by samer83** [comment]
what is the fix for this ? 
it gives the same error, do you have a solution ?

**Comment by burhan** [comment]
Hi, this means that the file you have provided is corrupted. Please check with your bank for an updated file.
